name: Build and test .NET-Project
on:
  pull_request:
    types: [opened, reopened, edited]

  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    ### Abweichend zur Vorlage wird hier der SQL-Server eingerichtet.
    
    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2017-latest

        ports:
          - 1433:1433

        env:
          ACCEPT_EULA: Y
          MSSQL_PID: Express
          MSSQL_LCID: 1031
          MSSQL_MEMORY_LIMIT_MB: 1024
          MSSQL_SA_PASSWORD: Sql2Admin

    ### Ende Abweichung

    steps:
      - name: Repository abrufen
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: GitHub privat Package registrieren
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Abhängigkeiten wiederherstellen
        run: dotnet restore

      - name: Projekt bauen
        run: dotnet build --no-restore --configuration Release

      - name: Tests ausführen
        run: dotnet test --no-build --configuration Release --verbosity normal